### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by devenes** [actions-js/push#11]
The GitHub Actions workflow gives the following annotation while running the action.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-js/push

**Comment by devenes** [comment]
Pull request has opened: #10

**Comment by notfilippo** [comment]
Closed by #10

**Comment by bhrajesh97** [comment]
i'm create  git to cpnale cicd and i don't know it working but i'm sacing thiss issue can you pleqase help me 
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: bhrajesh97/deployer@4.3.0

**Comment by devenes** [comment]
Hi @bhrajesh97,
> i'm create git to cpnale cicd and i don't know it working but i'm sacing thiss issue can you pleqase help me Node.js 12 actions are deprecated. For more information see: [github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Please update the following actions to use Node.js 16: bhrajesh97/deployer@4.3.0

It looks like updated to 16, https://github.com/bhrajesh97/deployer/commit/c7d02ea518fde94aa77e5c9347e9c07cbcdbe739 you can get a new release or you can use `bhrajesh97/deployer@master` since committed in the master branch.

**Comment by thomasmerz** [comment]
@notfilippo , can you please give the community a new release? Thanks a lot!

**Comment by ReenigneArcher** [comment]
Anything preventing a new release? This would be nice to have updated as I have a lot of workflows to get updated, as I'm sure many others do.

**Comment by devenes** [comment]
@notfilippo  👆

**Comment by notfilippo** [comment]
Released! Sorry for the wait @devenes @ReenigneArcher @thomasmerz

**Comment by devenes** [comment]
Thank you 🎉 @notfilippo

**Comment by JamesVanWaza** [comment]
@notfilippo, @devenes if I get the error, and the `firebase-hosting-merge.yml` and `firebase-hosting-pull-request.yml` is autogenerated, how do I fix it?

**Comment by devenes** [comment]
Hi @JamesVanWaza,

I checked your repositories and found that you are using some old version actions. You need to upgrade the version of the action:

- https://github.com/JamesVanWaza/algolia-instantsearch-demo/blob/master/.github/workflows/firebase-hosting-pull-request.yml#L13
- https://github.com/JamesVanWaza/algolia-instantsearch-demo/blob/master/.github/workflows/firebase-hosting-merge.yml#L15

Actually there is no new release of FirebaseExtended/action-hosting-deploy action so you can specify the branch name with using: `- uses: FirebaseExtended/action-hosting-deploy@main`

You can check my PR according the issue: https://github.com/JamesVanWaza/algolia-instantsearch-demo/pull/367

**Comment by JamesVanWaza** [comment]
Great just saw your PR. Will update them manually. Once the new release is out let us know.

**Comment by devenes** [comment]
I just realized that they updated the release with the action upgrade commit: https://github.com/FirebaseExtended/action-hosting-deploy/releases/tag/v0. So there is no problem about using `v0`. Your error must be because the `checkout` action.
