### ISSUE TITLE
Transition to Node 20

### ISSUE THREAD

**Issue by mcmikecreations** [actions-js/push#25]
I keep getting the warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions-js/push@master

As per [this reference](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) the action should be updated. Would that be possible?

**Comment by ImanMahmoudinasab** [comment]
@devenes I can work on this issue and create a PR. We will need to deploy a new major release.

**Comment by archon810** [comment]
I think it's time to update to node24.
