### ISSUE TITLE
Commit Message Format

### ISSUE THREAD

**Issue by erictaylor** [actions-js/push#3]
Commit message are coming out as "{Whatever message is provided}".

Suspect https://github.com/actions-js/push/blob/master/start.sh#L52 needs changed to `"${INPUT_MESSAGE}"` from `"{$INPUT_MESSAGE}"`.

**Comment by erictaylor** [comment]
PR #4

**Comment by bconnorwhite** [comment]
Bump

**Comment by filipporeds** [comment]
Finally merged :tada: !
