### ISSUE TITLE
Fails after latest release

### ISSUE THREAD

**Issue by abhijoshi2k** [actions-js/push#7]
The workflow fails after latest release.

For your reference: 
![image](https://user-images.githubusercontent.com/46530103/127904233-6e63c212-b9e3-43d1-90ea-c973e4cc590e.png)

**Comment by anastasiya-nalyhach** [comment]
I believe our failures are related to the last release changes: the default branch was changed from 'master' to 'main'.
Just add branch parameter to the yaml it helped me
![image](https://user-images.githubusercontent.com/85237959/128506877-6a8c6d80-108b-48df-b3e1-f347bdda62ea.png)

**Comment by abhijoshi2k** [comment]
Hey @anastasiya-nalyhach , thanks for your suggestion. I wish to tell you that it worked as expected now.
Thanks again for suggesting this solution. I'm closing this issue now.
